development:
  adapter: postgresql
  database: snowman_ldap
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: snowman_ldap
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: snowman_ldap
  pool: 5
  timeout: 5000

